language: node_js
node_js:
- 5.9.1
before_install:
- npm install
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: avH9vjuxzQLgDI66JOQp5kIRVw9Q4PEFqJUcL9J22/fxjMWD22bNrGhmwb12a+JE4D42im55PnW/Bi/seAYWunGjcxcBbhY23INUZ09zKRupna5dVhwdrrKfN3u9WJY9ZGtHaTiKGbRVUacPM9jc/Ujzj/64KpX8z60v6c5h8AKTuv0KXiFs59QPGZ5moYJ0985Q7NJbrzCUxZnyTMbcLP+3LlYCu/IK/05YzWgZnVzx9h6bJmCySPGMM/6SmAboq5hJPD5CTZJO9uwGb9iUHugV6oqTaMOlBUBr+Yu+BpriDXZnm036XIH1z3C4q+fFsSTUyQfWfGy02lGXZ9xp3/C8pCIxz7iFg8pWRvvBGJDJOl2OVIkJWoZ9+hLGHlIQ2/MFw5Vb6iPujbeZvJqmjJl+hNtJ8bZnT7rdklmK97sYWYn7HQtazNMeBRxAuJpqizgGo7zQ6COm1lyEQwYRZw6ahLgkcqNUPzhu29rwo+5MDBYXbaWu2C5ZoBeX52jz3g1OQl7Mpfdp9osU2Oszx4jbPxwG9WMHQFw3qVK/5V+st0h1AOqQFJd7eb9/bsLpmEusMkWlPpLwMjPJausowxR2XN68EeCJDxfTVbNMjHV9SFIhBpmbuQJJgCw013F6/qvK0a80GsQsDwA6XYT7rXXdIcNypSTunhbzJT11x9w=
  - secure: PD0XjdcmwuLyVQoNz3yFDOVqA4/Mf7cTRaVCIH9MfWCPsU6pajLoNd0LJjblM0vALLE62c33vCkvCGG16puOnn5jcg8qf1OUllJVBXZZUhIsyLscBL1lgzOODadEZS4e0gT26IhDuw1iOOdv0VAVGySUO58KMhePh6XWR6HmFkN25xywntz5EKG0FTepOMyLkbabryIensZbwerf5qPhonOjeCBtFRiCWLQp97aL0x8FCPdr+VE3a1To3OGRK9g0Ceb8odKjirj/eBqid5clbLir5QT8mPxy4Vs5gQ1KFBYetsn5Lzn2KwkyAk5FFDLscsZUZDSyVEMnGtUiPl6kc7MqIB0tb5o/WbaK0YONc6xE6y0pPD0r/TsfcyuPEbzYDEgVAGKkHqTrtOKTGc2a6BvA61zS4oLkrYz2EE8jPYOB+ayjbtC4r3fb/6ZGwAqBucubKFubzMXlWeRCDSuwFq3HGa5svfcQhxMh6KFW1qQzri1zxyP1Ezm4Pm4vZokTTPUOVHy/t2YlqJsStzHYqGw7InRe0D+ViqrLw+yOx19bAIgx4GJenXRocMcW3wZMwSfS9p8Ehq+JRjuVe/2JIdG2OOiJHOS2UeNf1eIyW7ppLgTRDUwqEmDIC6gfn8pLWwSZ/bXiXD5CWYj0KGPK8pe1xzzn5qCX6nwCyf9kqVc=
